# -*- coding: utf-8 -*-
"""도서관공모전_지오코딩_최종.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6WYZBfxrtu_NrTVMKEN8gP6HtJjIxRV
"""

import pandas as pd

df = pd.read_csv("df_final_matched_final.csv", encoding='cp949')



# folium import
import folium

import requests
import json

seoul_admin = pd.read_csv('서울시 행정구.csv')

import geopandas as gpd
from shapely import wkt

m1 = folium.Map(
    location=[37.559819, 126.963895],
    zoom_start=11,
    tiles='cartodbpositron'
)

# Convert the POLYGON WKT data to shapely geometries
seoul_admin['geometry'] = seoul_admin['polygon'].apply(wkt.loads)

# Create a GeoDataFrame and set the CRS
gdf = gpd.GeoDataFrame(seoul_admin, geometry='geometry', crs='epsg:4326') # Set the CRS here

# Add the polygons to the map
folium.GeoJson(gdf).add_to(m1)

# Define cluster colors
cluster_colors = {
    0: 'red',
    1: 'orange',
    2: 'green',
    3: 'blue',
    4: 'purple',
}

for index, row in df.iterrows():
      folium.Circle(
        location=[row['lib_x'], row['lib_y']],
        radius=150,
        color=cluster_colors.get(row['lib_num'], 'brown'),
        fill=True,
        fill_color=cluster_colors.get(row['lib_num'], 'brown')
    ).add_to(m1)

for index, row in df.iterrows():
    folium.Marker(
        location=[row['lib_x'], row['lib_y']],
              icon=folium.Icon('black', icon='book'),
        size=150
    ).add_to(m1)

# Add circles to the map
for _, row in df.iterrows():
    folium.Circle(
        location=(row['hos_x'], row['hos_y']),
        radius=75,
        color=cluster_colors.get(row['lib_num'], 'brown'),
        fill=True,
        fill_color=cluster_colors.get(row['lib_num'], 'brown')
    ).add_to(m1)

m1

# html 로 저장
m1.save('map.html')

