# -*- coding: utf-8 -*-
"""도서관공모전_정보나루API와인기대출도서2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zwY8ibu9s0-PgUOM2QKa-fh-Rkmtmol
"""

import pandas as pd

# Top100 기준

# 노원중앙도서관	111058 nwcentral 98종
# 서울특별시교육청노원평생학습관	111022 edu 98종
# 월계도서관	111085 moon 86종
# 불암도서관	111485 fire 94종
# 노원어린이도서관	111047 nwch X
# 상계도서관	111307 up 96종
# 화랑도서관	111239 hwa 83종
# 하계어린이도서관	111519 downch X
# 월계어린이도서관	111484 moonch 37종

# 60대 이상 스테디 대출 도서 top100
top100 = pd.read_csv('steady_60_100.csv', encoding='utf-8')

# 노원중앙도서관
jung = pd.read_csv('matched_isbn_nwcentral.csv', encoding='utf-8')
# 서울특별시교육청노원평생학습관
pyung = pd.read_csv('matched_isbn_edu.csv', encoding='utf-8')
# 월계도서관
wall= pd.read_csv('matched_isbn_moon.csv', encoding='utf-8')
# 불암도서관
bul = pd.read_csv('matched_isbn_fire.csv', encoding='utf-8')
# 상계도서관
sang = pd.read_csv('matched_isbn_up.csv', encoding='utf-8')
# 화랑도서관
hwa = pd.read_csv('matched_isbn_hwa.csv', encoding='utf-8')
# 월계어린이도서관
wallch = pd.read_csv('matched_isbn_moonch.csv', encoding='utf-8')

"""# 노원중앙"""

jung100 = top100.copy()

# Check if the 'ISBN' in steady_df exists in 'Matched ISBN' of matched_isbn_df
jung100['yes'] = jung100['ISBN'].apply(lambda x: 1 if x in jung['Matched ISBN'].values else 0)

# Display the first few rows of the updated DataFrame
jung100.head()

jung100['yes'].value_counts()

jung100['mul'] = jung100['yes'] * jung100['권']

jung100['mul'].value_counts()

jung100['mul'].sum()
